name: Publish Docker (on PR merge to main)

on:
  pull_request:
    branches: [ "master" ]
    types: [ "closed" ]
  push:
    tags: [ "v*.*.*" ]

env:
  DOCKERHUB_IMAGE: omarhossameldinkandil/apokrat
jobs:
  build-and-push:
    if: ${{ github.event_name == 'push' || (github.event.pull_request.merged == true) }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx (docker-container)
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: 'omarhossameldinkandil'
          password: 'dckr_pat_B4LDew9e7aCqyrtboi9oNYYbn2Q'

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKERHUB_IMAGE }}
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=ref,event=branch
            type=sha,prefix=sha-
            type=semver,pattern={{version}}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Running tests
        uses: docker/build-push-action@v6
        # to run testing with we write unit test

      - name: Deploying
        uses: docker/build-push-action@v6

